checkov

diff --git a/.github/workflows/prv_sub.yml b/.github/workflows/prv_sub.yml
--- a/.github/workflows/prv_sub.yml
+++ b/.github/workflows/prv_sub.yml
@@ -48,13 +48,13 @@ jobs:
   #     with: 
   #       framework: terraform
 
-    # Upload results to GitHub Advanced Security
-    # - name: Upload SARIF file
-    #   if: success() || failure()
-    #   uses: github/codeql-action/upload-sarif@v2
-    #   with:
-    #     sarif_file: results.sarif
-    #     category: checkov
+  #   # Upload results to GitHub Advanced Security
+  #   - name: Upload SARIF file
+  #     if: success() || failure()
+  #     uses: github/codeql-action/upload-sarif@v2
+  #     with:
+  #       sarif_file: results.sarif
+  #       category: checkov
 
   plan:
     name: 'Plan'
@@ -83,6 +83,21 @@ jobs:
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
       run: terraform init
+    
+    #checkov
+    - name: checkov
+      run: |
+        sudo apt update
+        sudo apt install software-properties-common
+        sudo add-apt-repository ppa:deadsnakes/ppa
+        sudo apt install python3.7
+        sudo apt install python3-pip
+        sudo python3.7 -m pip install -U checkov #to install or upgrade checkov)
+        source <(register-python-argcomplete checkov)
+        terraform init
+        terraform plan -out tf.plan
+        terraform show -json tf.plan  > tf.json 
+        checkov -f tf.json
 
     # Generates an execution plan for Terraform
     - name: Terraform Plan
@@ -148,32 +163,32 @@ jobs:
                 body: body
             })
   
-  apply:
-    name: 'Apply'
-    if: github.ref == 'refs/heads/main' 
-    runs-on: ubuntu-latest
-    environment: production
-    needs: plan
+  # apply:
+  #   name: 'Apply'
+  #   if: github.ref == 'refs/heads/main' 
+  #   runs-on: ubuntu-latest
+  #   environment: production
+  #   needs: plan
     
-    steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v3
+  #   steps:
+  #   # Checkout the repository to the GitHub Actions runner
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
 
-    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
+  #   # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+  #   - name: Setup Terraform
+  #     uses: hashicorp/setup-terraform@v2
 
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      run: terraform init
+  #   # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+  #   - name: Terraform Init
+  #     run: terraform init
 
-    # Download saved plan from artifacts  
-    - name: Download Terraform Plan
-      uses: actions/download-artifact@v3
-      with:
-        name: tfplan
+  #   # Download saved plan from artifacts  
+  #   - name: Download Terraform Plan
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: tfplan
 
-    # Terraform Apply
-    - name: Terraform Apply
-      run: terraform apply -auto-approve tfplan
+  #   # Terraform Apply
+  #   - name: Terraform Apply
+  #     run: terraform apply -auto-approve tfplan
