tesy2

diff --git a/.github/workflows/prv_sub.yml b/.github/workflows/prv_sub.yml
--- a/.github/workflows/prv_sub.yml
+++ b/.github/workflows/prv_sub.yml
@@ -30,8 +30,8 @@ jobs:
       run: terraform validate
 
     # Checks that all Terraform configuration files adhere to a canonical format
-    # - name: Terraform Format
-    #   run: terraform fmt -check -recursive
+    - name: Terraform Format
+      run: terraform fmt -check -recursive
     
     # Perform a security scan of the terraform code using checkov
     - name: Run Checkov action
@@ -41,12 +41,12 @@ jobs:
         framework: terraform
 
     # Upload results to GitHub Advanced Security
-    - name: Upload SARIF file
-      if: success() || failure()
-      uses: github/codeql-action/upload-sarif@v2
-      with:
-        sarif_file: results.sarif
-        category: checkov
+    # - name: Upload SARIF file
+    #   if: success() || failure()
+    #   uses: github/codeql-action/upload-sarif@v2
+    #   with:
+    #     sarif_file: results.sarif
+    #     category: checkov
 
   terraform:
     name: 'Terraform'
