check3

diff --git a/.github/workflows/prv_sub.yml b/.github/workflows/prv_sub.yml
--- a/.github/workflows/prv_sub.yml
+++ b/.github/workflows/prv_sub.yml
@@ -21,25 +21,25 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-  #   # Checkout the repository to the GitHub Actions runner
-  #   - name: Checkout
-  #     uses: actions/checkout@v3
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v3
 
-  #   # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-  #   - name: Setup Terraform
-  #     uses: hashicorp/setup-terraform@v2
+    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
 
-  #   # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-  #   - name: Terraform Init
-  #     run: terraform init -backend=false
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init -backend=false
 
-  #   # Validate terraform files
-  #   - name: Terraform Validate
-  #     run: terraform validate
+    # Validate terraform files
+    - name: Terraform Validate
+      run: terraform validate
 
-  #   # Checks that all Terraform configuration files adhere to a canonical format
-  #   # - name: Terraform Format
-  #   #   run: terraform fmt -check -recursive
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # - name: Terraform Format
+    #   run: terraform fmt -check -recursive
     
     # Perform a security scan of the terraform code using checkov
     - name: Run Checkov action
@@ -48,19 +48,18 @@ jobs:
       with: 
         framework: terraform
 
-  #   # Upload results to GitHub Advanced Security
-  #   - name: Upload SARIF file
-  #     if: success() || failure()
-  #     uses: github/codeql-action/upload-sarif@v2
-  #     with:
-  #       sarif_file: results.sarif
-  #       category: checkov
+    # # Upload results to GitHub Advanced Security
+    # - name: Upload SARIF file
+    #   if: success() || failure()
+    #   uses: github/codeql-action/upload-sarif@v2
+    #   with:
+    #     sarif_file: results.sarif
+    #     category: checkov
 
   plan:
     name: 'Plan'
     runs-on: ubuntu-latest
     environment: production
-    needs: checkov
     # needs: tests
     outputs:
       tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
